### ISSUE TITLE
observationtypes_list.html offers deleted ObservationTypes to add even after multiple refresh

### ISSUE THREAD

**Issue by managingwholes** [Soil-Carbon-Coalition/atlasbiowork#12]
this is the observationtype_list.html template (URL /observationtypes) which shows some deleted ObservationTypes, perhaps since last deploy

**Comment by sheppard** [comment]
Depending on your network speeds, it can take a few seconds for observationtypes.json to be re-fetched in the background when the app loads.  In the meantime the list view will use the previously stored version (which is what it uses when offline).  Note that the JSON data is stored in an IndexedDB via [wq/store.js](https://wq.io/docs/store-js) and is completely distinct from the build and application cache.  All JSON lists are refreshed whenever the app starts up and not only after a build.  If your app is offline (or there is an error retrieving the data) you will be stuck with the old lists, but otherwise it should generally be up to date.

A lot of this is completely transparent and behind the scenes.  On a desktop browser it helps to watch the network traffic in the developer toolbar, and also to enable wq.app debug logs by setting `config.debug = true` in main.js or config.js.   It would also be useful to have some additional indicators within the app itself of what was going on - see wq/wq.app#61 and wq/wq.app#62.
