### ISSUE TITLE
site_list.html

### ISSUE THREAD

**Issue by managingwholes** [Soil-Carbon-Coalition/atlasbiowork#13]
Please instruct me how to change this template and its behavior, as I would like to use it (link it) from the index template.

Currently the behavior on Android is that when you touch the map, or a marker on the map, the map zooms to your location.

On laptop, when you click on a marker, the site_popup.html is perfect. Would like something similar on mobile but perhaps larger.

I plan to add an Add Site button to this template.

**Comment by sheppard** [comment]
This is the same page linked to from "New Observation for Existing Site".  The behavior is mostly the default for list views: show a list of sites alongside a map of the same sites.  I collapsed the list behind a button, and changed the primary link for each item in the list to go to the observation type list, rather than directly to the site detail page.

I also changed the default map behavior to zoom to your location as soon as it starts up.  What is probably happening on mobile is that it is finding your location at the exact time when you touch the map, whereas on the desktop it isn't finding your location at all.  In either case, once the zoom settles you should be able to tap a marker and get the popup.

The code I added is in [config.js](https://github.com/Soil-Carbon-Coalition/atlasbiowork/blob/master/app/js/atlasbiowork/config.js#L45-L50).  The current location locate max zoom level is probably way too high - if you turn that down to say 10 or so it might be a bit easier to use - it will still zoom to your location but you'll be more likely to see nearby sites.  (See http://leafletjs.com/reference.html#map-locate-options)
