### ISSUE TITLE
second installation. ImportError: no module named 'wq.db.rest.compat'

### ISSUE THREAD

**Issue by managingwholes** [Soil-Carbon-Coalition/atlasbiowork#19]
after I ran migrate.py on a new install of codebase following the readme

**Comment by sheppard** [comment]
I moved that import to a different module in the latest wq.db master.  It should be working now, though you'll want to update to the latest wq.app and wq.db again to avoid some other issues that cropped up.  This will be easier to manage once I tag the next release (since we'll be able to pin the requirements.txt to specific wq module versions).
