### ISSUE TITLE
simple photo with coordinates

### ISSUE THREAD

**Issue by managingwholes** [Soil-Carbon-Coalition/atlasbiowork#20]
One oft-requested feature doesn't correspond to data models. That would be a simple photo with coordinates, date, and description, no site name needed. 

Could something like this be done at a template level, that would create both a site and an observation (simple photo) in one screen? If we need a site name, the template could name it after the date (non unique).

**Comment by sheppard** [comment]
Yes, this can be done at the template level with a bit of customization.  We would just need another screen like the custom `locate` view, but with the form posting to `/observations/` directly rather than being handled by JavaScript as in the `locate` view.

Another way to do this would be to create a new model, `PhotoObservation` or similar, that has its own location field and doesn't need to reference the `Site` model.  You could then use the default list/detail/edit template structure for that model.

**Comment by managingwholes** [comment]
Would this issue relate somehow to the **needed support for multiple photos**, perhaps in the sense that photo fields might be added and labeled and edited somewhat like text or number fields? See also issue [#10](https://github.com/Soil-Carbon-Coalition/atlasbiowork/issues/10) 

That said, I think the PhotoObservation model makes sense as this will be popular and often used.

**Comment by managingwholes** [comment]
On second thought, we want to emphasize repeatable photos so the distinction between site and observation should be maintained.
