### ISSUE TITLE
favicon and shortcut icons

### ISSUE THREAD

**Issue by managingwholes** [Soil-Carbon-Coalition/atlasbiowork#22]
If I put these in htdocs they get removed with each deploy. Where should I put them so I can alias them properly in the apache conf file?

**Comment by sheppard** [comment]
Everything in `htdocs/` is generated from a copy of `app/`, so if you want to make a permanent change to `htdocs/` you can just put the files in `app/` and it will go out with the next build.  There should already be `favicon.ico` alias in the Apache conf.  If you put the rest of the shortcut icons in the `images/` folder you won't need to create additional aliases for them.

A typical static website wouldn't need the aliases at all, since the `DocumentRoot` is already pointing to the `htdocs/` folder.  The challenge with wq is that the website and REST API [are the same](https://wq.io/docs/website-rest-api), and so the URL paths for the static files and the WSGI application are intermingled.  The workaround I've come up with is to use aliases for everything in the root folder.

Eventually I would like to include some default icons with the project template so it is clear what to override (see wq/wq.start#1).  I would also like to make it easier to run the site directly off of `app/` which will be useful for debugging (see wq/wq.start#21).
