### ISSUE TITLE
"Add observation" to site yields server error

### ISSUE THREAD

**Issue by managingwholes** [Soil-Carbon-Coalition/atlasbiowork#23]
I added a New site + observation. Then I clicked on Sites, chose a site, and Add observation. After I chose observation type  (URL as follows)

https://atlasbiowork.com/observations/new?type_id=4&site_id=32

the site shown greyed out in the Site field was the one I had last entered, NOT the site with id=32. 

When I tried to sync observation, got a 500.

**Comment by managingwholes** [comment]
The above error still happens. 

In general, there is something wrong about navigation from the Sites list. When I click on a site from the sites list, I go to ObservationTypes for the site, rather than to /sites/sitenumber.

Where can I fix this?

**Comment by sheppard** [comment]
There are two issues:

First, the New site + observation flow currently caches the site information in a "site_data" template variable that is present even on subsequent observations.  This is causing an error when saving the second observation since the new site was already created.  One way to fix this would be to modify the logic in `observation_edit.html`: if `{{#site_id}}` is defined, use that information instead of the cached `{{#site_data}}`.

``` diff
+ {{#site_id}}
+ <li class="ui-field-contain">
+   <label for="site_id_label">Site</label>
+   <input id="site_id_label" value="{{#site}}{{label}}{{/site}}" disabled>
+   <input type="hidden" name="site_id" value="{{site_id}}">
+   <p class="error observation-site_id-errors"></p>
+ </li>
+ {{/site_id}}
+ {{^site_id}}
  {{#site_data}}
  <li class="ui-field-contain">
    <label for="site_data_label">Site</label>
    <input id="site_data_label" value="{{site_data_label}}" disabled>
    <input type="hidden" name="site_data" value="{{site_data}}">
  </li>
  {{/site_data}}
  {{^site_data}}
  <li class="ui-field-contain">
    <label for="site_id">Site</label>
    <select id="site_id" name="site_id" required>
      <option value="">Select a site...</option>
      {{#site_list}}
        {{>option}}
      {{/site_list}}
    </select>
    <p class="error observation-site_id-errors"></p>
  </li>
  {{/site_data}}
+ {{/site_id}}
```

The second issue is just an artifact of how I set up the `site_list.html` template.  The primary link goes to the observationtypes page, while, the secondary link goes to /sites/sitenumber.  Feel free to switch these around, e.g. to something like this:

``` diff
  {{#list}}
  <li>
-   <a href="{{rt}}/observationtypes/?site_id={{id}}">
+   <a href="{{rt}}/sites/{{id}}">
      <h3>{{label}}</h3>
    </a>
-   <a href="{{rt}}/sites/{{id}}" data-icon="info">
-     Site Info
+   <a href="{{rt}}/observationtypes/?site_id={{id}}" data-icon="plus">
+     Add Observation
    </a>
  </li>
  {{/list}}
```

You could also just remove the second link entirely.
