### ISSUE TITLE
map tiles no longer loading; mapquest wants a key

### ISSUE THREAD

**Issue by managingwholes** [Soil-Carbon-Coalition/atlasbiowork#27]
Mapquest wants a key for their tiles now as of July 11. Can't find tile requests in atlasbiowork; are the tile requests somewhere in the wq framework?

see goo.gl/xB0xXt

**Comment by sheppard** [comment]
Yes, there is a default configuration for basemap tiles built into wq, but it can be overridden by setting a configuration for [wq/map.js](https://wq.io/docs/map-js) in atliasbiowork/config.js.  There are two ways to do this.

## Custom Tile URL

In theory, you can just add a custom URL for the built in [L.TileLayer](http://leafletjs.com/reference.html#tilelayer) implementation.

``` javascript
config.map = {
    'bounds': [[49, -122], [25, -66]],
    'basemaps': [
        {
            'name': "Street",
            'type': 'tile',
            'url': 'http://custom-tile-url/',
        }
    ]
};
```

## Custom Layer Type

If you are going to use a custom basemap provider (such as Mapquest or MapBox), you might be able to figure out how to put your token in a custom URL above.  Otherwise, you may need to load their JavaScript and pre-register their custom layer type with wq/map.js in order to get it to work.

``` javascript
// atlasbiowork/thirdparty.js
define(['wq/map', 'third-party-plugin'],
function(map, TP) {
    map.addBasemapType('third-party-basemap', function(conf) {
        return TP.customLayer(conf);
    });
});
```

``` javascript
// atlasbiowork/main.js
define(['wq/app', ..., './thirdparty'], function(...
```

``` javascript
// atlasbiowork/config.js
// ...
config.map = {
    'bounds': [[49, -122], [25, -66]],
    'basemaps': [
        {
            'name': "Street",
            'type': 'third-party-basemap'
        }
    ]
};
// ...
```

Based on the little research I've done so far this will be easier to accomplish with mapbox.js (which is open source) than with MapQuest's plugin.

Looks like I'm going to have to change the documentation and defaults in wq/map.js...

**Comment by managingwholes** [comment]
the finish line continues to recede into the distance . . . 

I'm unsure of what goes where. Mapbox suggests using these headers to keep using a particular version of Leaflet:

```
<script src='https://api.mapbox.com/mapbox.js/v2.4.0/mapbox.standalone.js'></script>
<link href='https://api.mapbox.com/mapbox.js/v2.4.0/mapbox.css' rel='stylesheet' />
```

and the access token goes before the L.mapbox.map call:

`L.mapbox.accessToken ='pk.BLAHBLAH`

**Comment by sheppard** [comment]
Okay, it looks like we can do what we need with a custom tile URL (rather than integrating mapbox.js which, as you've discovered, is quite a bit more involved).  The `L.tileLayer` example in the Leaflet quick start guide happens to have the exact URL we need:
http://leafletjs.com/examples/quick-start.html

Since wq/map.js is using `L.tileLayer` under the hood, you should be able to get something working by just changing your config.js:

``` javascript
config.map = {
    'bounds': [[49, -122], [25, -66]],
    'basemaps': [
        {
            'name': "Street",
            'type': 'tile',
            'url': 'https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}',
            'id': 'mapbox.streets',
            'accessToken': "(your access token here)"
        }
    ]
};
```

If you want to avoid committing your access token into the repository I can show you how to put it in `local_settings.py` and pull it in through the configuration object.

**Comment by managingwholes** [comment]
Yes, please show me how to pull access token in through config object. 

In the meantime I'm using Thunderforest landscape tiles, a kind of topo map with world coverage. For our app we really need an aerial, preferably world; topo map is second choice and street maps third. 

Here's a call to a satellite layer with an access token that would require headers, from instructions at
https://www.mapbox.com/mapbox-gl-js/example/satellite-map/

`<script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.20.1/mapbox-gl.js'></script>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.20.1/mapbox-gl.css' rel='stylesheet' />`

`mapboxgl.accessToken = 'pk.eyJ....JQ';
var map = new mapboxgl.Map({
    container: 'map',
    zoom: 9,
    center: [137.9150899566626, 36.25956997955441],
    style: 'mapbox://styles/mapbox/satellite-v9',
    hash: false
});`

**Comment by managingwholes** [comment]
Or, possibly somewhat shaky re google's TOS, but this (found on SO) works on

[the paicines ranch map](https://atlasbiowork.com/map/paicines.html)

`var satellite = L.tileLayer('http://{s}.google.com/vt/lyrs=s,h&x={x}&y={y}&z={z}',{
                maxZoom: 20,
                subdomains:['mt0','mt1','mt2','mt3']
            });`

**Comment by sheppard** [comment]
Ok, I just made the [same change](https://github.com/powered-by-wq/wq.io/commit/ad35bffe1514644e0bd978b5e79275ac2c312ea1) to the wq documentation site anyway:
1. Define `MAPBOX_TOKEN` in `atlasbiowork/local_settings.py`
2. In `obs/rest.py`, add the following:
   
   ``` python
   # near the top
   from django.conf import settings
   
   # near the bottom
   rest.router.set_extra_config(
       mapbox_token=settings.MAPBOX_TOKEN,
   )
   ```
   
   This will make the setting available in the server-generated config data.
3. Define the basemaps in `app/js/atlasbiowork/config.js`:

``` javascript
var attrib = 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>';
var mapbox = 'https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}';

// Map defaults
config.map = {
    'bounds': [[49, -122], [25, -66]],
    'basemaps': [{
        'name': 'MapBox Satellite',
        'type': 'tile',
        'url': mapbox,
        'id': 'mapbox.satellite',
        'accessToken': config.mapbox_token,
        'attribution': attrib
    }, {
        'name': 'MapBox Streets',
        'type': 'tile',
        'url': mapbox,
        'id': 'mapbox.streets',
        'accessToken': config.mapbox_token,
        'attribution': attrib
    }]
};
```

I put the satellite layer first in this example to make it the default.  I believe it's the same layer shown in the MapBox GL JS example.

**Comment by managingwholes** [comment]
Good. Mapbox streets does a nice job of showing terrain and rivers.
