### ISSUE TITLE
map display in observation detail template for child observations

### ISSUE THREAD

**Issue by managingwholes** [Soil-Carbon-Coalition/atlasbiowork#30]
How could we show map in observation_detail when the observation is a child observation, at however many removes?

<div class="map detail-map" id="observation-{{id}}-map"></div> 

in
https://github.com/Soil-Carbon-Coalition/atlasbiowork/blob/master/templates/observation_detail.html#L32

For example, show a site map rather than an observation map.

**Comment by sheppard** [comment]
This should have been working, since we're carrying the site id forward to each child observation.  It looks like there was a bug in wq.db that I fixed with [this patch](https://github.com/wq/wq.db/commit/b66cedf173fe5bca1416d3f3f0ae7e82b9b2812a).  I think you should be fine upgrading to the master version on your current machine:

``` bash
sudo pip3 install https://github.com/wq/xlsform-converter/archive/master.zip
```

You can also wait until I finish the other upgrades and update requirements.txt.
